version: "3.9"

services:
  iat-api:
    image: iat-api:1.0.0
    build:
      context: ./backend/
      target: api
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/svr3/iat-api-logs:/usr/src/app/logs
      - images:/usr/src/app/images:rw
    env_file:
      - backend/env/test.env
    networks:
      - iat-front-end-net
      - iat-db-net
      - iat-redis-net
    depends_on:
      - iat-db
      - iat-redis
      - iat-worker

  iat-worker:
    image: iat-worker:1.0.0
    container_name: iat-worker
    build:
      context: ./backend/
      target: worker
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - images:/usr/src/app/images:rw
    env_file:
      - backend/env/test.env
    networks:
      - iat-front-end-net
      - iat-db-net
      - iat-redis-net
    depends_on:
      - iat-db
      - iat-redis

  iat-db:
    container_name: iat-db
    image: mariadb:11.0.2
    volumes:
      - iat-db-data:/var/lib/mysql
      - ./DATA/db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    env_file:
      - ./backend/env/test.env
    networks:
      - iat-db-net

  iat-nginx:
    container_name: iat-nginx
    image: iat-nginx:1.0.0
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.test
    restart: on-failure:5
    env_file:
      - ./backend/env/test.env
    # depends_on:
    #   - iat-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - iat-nginx-letsencrypt:/etc/letsencrypt
      - images:/usr/share/nginx/html/images:ro
    networks:
      - iat-front-end-net
      - iat-app-net

  iat-adminer:
    container_name: iat-adminer
    image: adminer:4.8.1
    restart: unless-stopped
    networks:
      - iat-db-net
      - iat-front-end-net

  iat-redis:
    image: redis:7.0.5
    container_name: iat-redis
    hostname: redis
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "4096"
    command:
      - /bin/sh
      - -c
      - redis-server --bind iat-redis --requirepass "${REDIS_PASSWORD}" --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    environment:
      REDIS_HOST: iat-redis
    env_file:
      - ./backend/env/test.env
    # ports:
    #   - ${REDIS_PORT}:6379
    networks:
      - iat-redis-net

networks:
  iat-db-net:
  iat-front-end-net:
  iat-redis-net:
  iat-app-net:

volumes:
  iat-nginx-letsencrypt:
  iat-db-data:
  images:
