services:
  iat-api:
    container_name: iat-api
    build:
      context: ./backend/
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /etc/localtime:/etc/localtime
      - iat_api_node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    restart: unless-stopped
    command: npm run start:api:dev
    depends_on:
      - iat-db
    networks:
      - iat-front-end-net
      - iat-db-net
      - iat-redis-net

  iat-worker:
    container_name: iat-worker
    build:
      context: ./backend/
      target: development
    volumes:
      - ./backend:/usr/src/app
      - iat_api_node_modules:/app/node_modules
      - /etc/localtime:/etc/localtime
    environment:
      NODE_ENV: development
    restart: unless-stopped
    command: npm run start:job:dev
    networks:
      - iat-front-end-net
      - iat-db-net
      - iat-redis-net

  iat-db:
    container_name: iat-db
    image: mariadb:11.0.2
    volumes:
      - ./DATA/db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    env_file:
      - ./backend/env/development.env
    networks:
      - iat-db-net

  # iat-admin:
  #   container_name: iat-admin
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./apps/
  #     args:
  #       UID: $USER_ID
  #       GID: $GROUP_ID
  #   volumes:
  #     - ./apps:/app
  #     - iat_ui_node_modules:/app/node_modules
  #     - /etc/localtime:/etc/localtime
  #   command: npm run start:admin
  #   restart: on-failure:5
  #   depends_on:
  #     - iat-api
  #   ports:
  #     - 4200:4200
  #   networks:
  #     - iat-front-end-net

  # iat-customer:
  #   container_name: iat-customer
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./apps/
  #     args:
  #       UID: $USER_ID
  #       GID: $GROUP_ID
  #   volumes:
  #     - ./apps:/app
  #     - iat_ui_node_modules:/app/node_modules
  #     - /etc/localtime:/etc/localtime
  #   command: npm run start:customer
  #   restart: on-failure:5
  #   depends_on:
  #     - iat-api
  #   ports:
  #     - "4201:4201"
  #   networks:
  #     - iat-front-end-net

  iat-nginx:
    container_name: iat-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.dev
      args:
        UID: $USER_ID
        GID: $GROUP_ID
    restart: on-failure:5
    environment:
      NODE_ENV: development
    env_file:
      - ./backend/env/development.env
    ports:
      - 80:80
    networks:
      - iat-front-end-net

  iat-adminer:
    container_name: iat-adminer
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8085:8080
    networks:
      - iat-db-net
      - iat-front-end-net

  iat-redis:
    image: redis:7.0.12
    container_name: iat-redis
    hostname: redis
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "4096"
    command:
      - /bin/sh
      - -c
      - redis-server --bind iat-redis --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    environment:
      REDIS_HOST: iat-redis
    env_file:
      - ./backend/env/development.env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - iat-redis-net

  iat-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: iat-redis-commander
    env_file:
      - ./backend/env/development.env
    environment:
      REDIS_HOSTS: iat-redis
      REDIS_HOST: iat-redis
      REDIS_PORT: iat-redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_HTTP_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_HTTP_PASSWORD}
    ports:
      - 8086:8081
    networks:
      - iat-front-end-net
      - iat-redis-net

networks:
  iat-db-net:
  iat-front-end-net:
  iat-redis-net:
    driver: bridge
volumes:
  iat_api_node_modules:
  iat_ui_node_modules:
    # docker-compose --env-file ./backend/env/development.env -p iat -f ./docker-compose.dev.yml up --build -d
    # docker-compose --env-file ./backend/env/development.env -f ./docker-compose.dev.yml build
